include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    # - custom_lint
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    avoid_positional_boolean_parameters: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
