name: evlve
description: Evlve
version: 1.0.0+0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.10.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path: ^1.9.0
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.6.0
  screen_brightness: ^2.0.0+2
  sensors_plus: ^6.1.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  smart_auth: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/launch-image.png
  branding: assets/branding.png

  color_dark: "#121212"
  image_dark: assets/launch-image-dark.png
  branding_dark: assets/branding-dark.png

  android_12:
    image: assets/launch-image.png
    icon_background_color: "#ffffff"

    image_dark: assets/launch-image-dark.png
    icon_background_color_dark: "#121212"

  web: false
