name: evlve
description: Evlve
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.3
  calendar_timeline: ^1.1.2
  dio: ^5.1.2
  duration_picker: ^1.1.1
  flex_color_picker: ^3.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  pinput: ^2.2.31
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.1.1
  sensors_plus: ^3.0.1
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0

dependency_overrides:
  # For compatability with Awesome Notifications
  # https://github.com/rafaelsetragni/awesome_notifications/issues/774
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  go_router_builder: ^2.0.2
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

