name: evlve
description: Evlve
version: 1.0.0+0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  cached_network_image: ^3.2.3
  collection: ^1.18.0
  dio: ^5.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path: ^1.8.3
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.2.0
  screen_brightness: ^1.0.0
  sensors_plus: ^5.0.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  smart_auth: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.0
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.0
  json_serializable: ^6.7.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/launch-image.png
  branding: assets/branding.png

  color_dark: "#121212"
  image_dark: assets/launch-image-dark.png
  branding_dark: assets/branding-dark.png

  android_12:
    image: assets/launch-image.png
    icon_background_color: "#ffffff"

    image_dark: assets/launch-image-dark.png
    icon_background_color_dark: "#121212"

  web: false
