name: evlve
description: Evlve
version: 1.0.0+7
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.3
  calendar_timeline: ^1.1.2
  dio: ^5.1.2
  duration_picker: ^1.1.1
  flex_color_picker: ^3.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.2.0
  go_router: ^10.0.0
  google_fonts: ^5.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  pinput: ^2.2.31
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.1.1
  screen_brightness: ^0.2.2
  sensors_plus: ^3.0.1
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0

dependency_overrides:
  # https://github.com/Baseflow/flutter_cached_network_image/issues/843
  http: ^1.0.0
  # https://github.com/rafaelsetragni/awesome_notifications/issues/774
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#fefbff"
  image: assets/launch-image.png
  color_dark: "#1b1b1f"
  image_dark: assets/launch-image-dark.png
  branding: assets/branding.png
  branding_dark: assets/branding-dark.png

  android_12:
    image: assets/launch-image.png
    icon_background_color: "#fefbff"
    image_dark: assets/launch-image-dark.png
    icon_background_color_dark: "#1b1b1f"

  web: false
