name: evlve
description: Evlve
version: 1.0.0+19
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.5
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  dio: ^5.3.3
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.2.0
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path: ^1.8.3
  pinput: ^3.0.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.1.5
  screen_brightness: ^0.2.2
  sensors_plus: ^3.0.1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.5.3
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  go_router_builder: ^2.3.0
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.1
  very_good_analysis: ^5.1.0

dependency_overrides: 
  # https://github.com/rafaelsetragni/awesome_notifications/issues/860
  awesome_notifications: 0.7.6

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/launch-image.png
  branding: assets/branding.png

  color_dark: "#121212"
  image_dark: assets/launch-image-dark.png
  branding_dark: assets/branding-dark.png

  android_12:
    image: assets/launch-image.png
    icon_background_color: "#ffffff"

    image_dark: assets/launch-image-dark.png
    icon_background_color_dark: "#121212"

  web: false